title: 'MUH IQBAL H, S.T.'
description: "Profil dan Riwayat Hidup"
baseurl: "/"
image: "/WKD06797.JPG"
url: "https://iqbal-hanafi.github.io"

header_pages:
  - index.md
  - projects.md

style: dark

footer: 'follow me on <a href="https://ig.me/ikbal.rdmc__">instagram</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
